FROM python:3.10-slim
WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir \
    flask \
    pymongo \
    notebook \
    jupyter-dash \
    dash \
    pandas \
    dash-leaflet \
    plotly

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
